version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_DB: organizacional_db
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: pass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
